env:
  es6: true
  browser: true
  node: true
parserOptions: # http://eslint.org/docs/user-guide/configuring.html#specifying-parser-options
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
plugins:
  - react
  - import
settings:
  import/resolver:
    webpack: { config: 'main/app/js/webpack.config.js' }
rules:
  # react/forbid-prop-types: [2, {forbid: [any]}]
  # react/jsx-handler-names: [2, {eventHandlerPrefix: handle, eventHandlerPropPrefix: on}]
  array-bracket-spacing: [2, never]
  arrow-parens: 0
  arrow-spacing: 2
  brace-style: [2, 1tbs, {allowSingleLine: true}]
  comma-dangle: [2, always-multiline]
  comma-spacing: 2
  comma-style: [2, last]
  computed-property-spacing: [2, never]
  consistent-return: 2
  constructor-super: 2
  curly: [2, multi-line]
  default-case: 2
  dot-notation: 2
  eol-last: 2
  eqeqeq: 2
  generator-star-spacing: [2, after]
  import/no-unresolved: 2
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  import/no-mutable-exports: 2
  import/no-extraneous-dependencies: 2
  import/no-duplicates: 2
  import/extensions: [2, {js: never}]
  indent: [2, 4, {SwitchCase: 1}]
  jsx-quotes: [2, prefer-double]
  key-spacing: [2, {beforeColon: false, afterColon: true}]
  keyword-spacing: 2
  linebreak-style: [2, unix]
  new-cap: [2, {newIsCap: true, capIsNew: false}]
  new-parens: 2
  no-alert: 0
  no-array-constructor: 2
  no-caller: 2
  no-catch-shadow: 0 # this is only relevant for IE8
  no-class-assign: 2
  no-cond-assign: 2
  no-console: 0
  no-const-assign: 2
  no-constant-condition: 2
  no-continue: 2
  no-debugger: 2
  no-delete-var: 2
  no-dupe-args: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-empty: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-boolean-cast: 2
  no-extra-semi: 2
  no-fallthrough: 2
  no-floating-decimal: 2
  no-implied-eval: 2
  no-inner-declarations: [2, both]
  no-invalid-regexp: 2
  no-irregular-whitespace: 2
  no-iterator: 2
  no-labels: 2
  no-lone-blocks: 2
  no-lonely-if: 2
  no-loop-func: 2
  no-mixed-spaces-and-tabs: 2
  no-multi-spaces: 2
  no-native-reassign: 2
  no-negated-in-lhs: 2
  no-new-func: 2
  no-new-object: 2
  no-new-wrappers: 2
  no-new: 2
  no-obj-calls: 2
  no-octal: 2
  no-proto: 2
  no-redeclare: 2
  no-return-assign: 2
  no-shadow-restricted-names: 2
  no-shadow: 0
  no-spaced-func: 2
  no-sparse-arrays: 2
  no-this-before-super: 2
  no-trailing-spaces: 2
  no-undef-init: 2
  no-undef: 2
  no-underscore-dangle: 2
  no-unreachable: 2
  no-unused-expressions: 2
  no-unused-vars: [2, {vars: all, args: after-used}]
  no-use-before-define: 2
  no-var: 2
  no-with: 2
  object-curly-spacing: [2, never]
  operator-linebreak: [2, before]
  prefer-arrow-callback: 2
  prefer-const: 2
  prefer-spread: 2
  prefer-template: 0
  quotes: [2, single, avoid-escape]
  react/display-name: [2, {ignoreTranspilerName: false}]
  react/jsx-boolean-value: 2
  react/jsx-closing-bracket-location: 2
  react/jsx-curly-spacing: 2
  react/jsx-indent-props: 2
  react/jsx-max-props-per-line: 0
  react/jsx-no-duplicate-props: 2
  react/jsx-no-literals: 0
  react/jsx-no-undef: 2
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  react/no-danger: 2
  react/no-did-mount-set-state: 0 # useful to animate after rendering
  react/no-did-update-set-state: 2
  react/no-direct-mutation-state: 2
  react/no-multi-comp: 0
  react/no-set-state: 0
  react/no-unknown-property: 2
  react/react-in-jsx-scope: 2
  react/require-extension: 2
  react/self-closing-comp: 2
  react/sort-comp: 2
  react/sort-prop-types: 2
  react/wrap-multilines: 2
  semi-spacing: 2
  semi: [2, always]
  space-before-function-paren: [2, {anonymous: always, named: never}]
  space-in-parens: [2, never]
  space-infix-ops: [2, {int32Hint: true}]
  space-unary-ops: 2
  strict: [2, global]
  use-isnan: 2
  valid-typeof: 2
  wrap-iife: [2, inside]
  wrap-regex: 2
  yoda: 0
